title: Beginner HTML/CSS Sushi Cards
hero_image: images/banner.png
description: Learn to make a website
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3
listed: false
ingredient: false
copyedit: true
curriculum: 0, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: animals, humour, space, photography, music, games
technologies: html-css-javascript
site_areas: coderdojo
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Getting set up
- title: Your first webpage!
- title: Controlling how it looks
- title: Adding pictures
- title: Adding a map or video
- title: Making a list
- title: Creating links
- title: Adding more pages
- title: Navigating your website
- title: Making a menu bar
- title: Styling the menu bar
- title: Adding a table