title: cd-sebento-htmlcss-1
hero_image: images/banner.png
description: cd-sebento-htmlcss-1 description
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 0, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: animals, art, humour, space, photography, outdoors, music, games
technologies: electronic-components, sense-hat, html-css-javascript, scratch, python
site_areas: coderdojo
hardware: electronic-components, sense-hat
software: html-css-javascript, scratch, python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Getting setup
- title: Your first web page!
- title: Controlling how it looks
- title: Adding pictures
- title: Adding a map or video
- title: Making a list
- title: Creating links
- title: Adding more pages
- title: Navigating your website
- title: Making a menu bar
- title: Styling the menu bar
- title: Adding a table