---
title: Bird watch website 1.0
hero_image: images/banner.png
description: Learn to make a website
theme: navy #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3.0.0
last_tested: 2018-05-01
steps:
  - 
    title: Introduction
  - 
    title: Getting set up
  - 
    title: Your first webpage!
  - 
    title: Controlling how it looks
  - 
    title: Adding pictures
  - 
    title: Adding a map or video
  - 
    title: Making a list
  - 
    title: Creating links
  - 
    title: Adding more pages
  - 
    title: Navigating your website
  - 
    title: Making a menu bar
  - 
    title: Styling the menu bar
  - 
    title: Adding a table
